-- ==============================================================================
-- SISTEMA: TicketCore (Gestão e Comercialização de Ingressos)
-- SGBD: PostgreSQL
-- VERSÃO: 1.2
-- ALTERAÇÕES v1.2: Seed completo com categorias, eventos, tipos de ingresso, transação, ingresso e notificações de exemplo
-- ==============================================================================

-- ==========================================
-- PARTE 1: SCRIPT DDL (Criação das Tabelas)
-- ==========================================

CREATE TABLE USU_usuario (
    usu_id_usuario   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    usu_nm_usuario   VARCHAR(150) NOT NULL,
    usu_ds_email     VARCHAR(255) NOT NULL UNIQUE,
    usu_ds_senha     VARCHAR(255) NOT NULL,
    usu_nu_cpf_cnpj  VARCHAR(14)  NOT NULL UNIQUE,
    usu_ds_foto_perfil TEXT,
    usu_dt_cadastro  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PER_perfil (
    per_id_perfil  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    per_nm_perfil  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USP_usuario_perfil (
    usp_id_usuario BIGINT NOT NULL,
    usp_id_perfil  BIGINT NOT NULL,
    PRIMARY KEY (usp_id_usuario, usp_id_perfil),
    FOREIGN KEY (usp_id_usuario) REFERENCES USU_usuario(usu_id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (usp_id_perfil)  REFERENCES PER_perfil(per_id_perfil)   ON DELETE CASCADE
);

CREATE TABLE CAT_categoria (
    cat_id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    cat_nm_categoria VARCHAR(100) NOT NULL,
    cat_ds_categoria TEXT
);

CREATE TABLE EVE_evento (
    eve_id_evento    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    eve_id_organizador BIGINT  NOT NULL,
    eve_id_categoria   BIGINT  NOT NULL,
    eve_nm_evento    VARCHAR(200) NOT NULL,
    eve_dt_evento    TIMESTAMP   NOT NULL,
    eve_nm_local     VARCHAR(200) NOT NULL,
    eve_qt_capacidade INTEGER     NOT NULL CHECK (eve_qt_capacidade > 0),
    eve_ds_imagem    TEXT,
    FOREIGN KEY (eve_id_organizador) REFERENCES USU_usuario(usu_id_usuario),
    FOREIGN KEY (eve_id_categoria)   REFERENCES CAT_categoria(cat_id_categoria)
);

CREATE TABLE TPI_tipo_ingresso (
    tpi_id_tipo_ingresso BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    tpi_id_evento        BIGINT         NOT NULL,
    tpi_nm_tipo          VARCHAR(100)   NOT NULL,
    tpi_vl_preco         NUMERIC(10,2)  NOT NULL CHECK (tpi_vl_preco >= 0),
    tpi_qt_lote          INTEGER        NOT NULL CHECK (tpi_qt_lote > 0),
    FOREIGN KEY (tpi_id_evento) REFERENCES EVE_evento(eve_id_evento) ON DELETE CASCADE
);

CREATE TABLE TRA_transacao (
    tra_id_transacao  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    tra_id_comprador  BIGINT        NOT NULL,
    tra_dt_transacao  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    tra_st_transacao  CHAR(1)       NOT NULL DEFAULT 'P' CHECK (tra_st_transacao IN ('C', 'P', 'X')),
    tra_vl_total      NUMERIC(10,2) NOT NULL CHECK (tra_vl_total >= 0),
    FOREIGN KEY (tra_id_comprador) REFERENCES USU_usuario(usu_id_usuario)
);

CREATE TABLE ING_ingresso (
    ing_id_ingresso      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    ing_id_transacao     BIGINT      NOT NULL,
    ing_id_tipo_ingresso BIGINT      NOT NULL,
    ing_cd_acesso        VARCHAR(50) NOT NULL UNIQUE,
    ing_st_ingresso      CHAR(1)     NOT NULL DEFAULT 'A' CHECK (ing_st_ingresso IN ('A', 'U', 'C')),
    FOREIGN KEY (ing_id_transacao)     REFERENCES TRA_transacao(tra_id_transacao),
    FOREIGN KEY (ing_id_tipo_ingresso) REFERENCES TPI_tipo_ingresso(tpi_id_tipo_ingresso)
);

CREATE TABLE NOT_notificacao (
    not_id_notificacao BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000001) PRIMARY KEY,
    not_id_usuario     BIGINT    NOT NULL,
    not_ds_mensagem    TEXT      NOT NULL,
    not_ch_lida        CHAR(1)   NOT NULL DEFAULT 'N' CHECK (not_ch_lida IN ('S', 'N')),
    not_dt_criacao     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (not_id_usuario) REFERENCES USU_usuario(usu_id_usuario) ON DELETE CASCADE
);


-- ==========================================
-- PARTE 2: ÍNDICES
-- ==========================================

CREATE INDEX IDX_ing_transacao   ON ING_ingresso(ing_id_transacao);
CREATE INDEX IDX_ing_tipo        ON ING_ingresso(ing_id_tipo_ingresso);
CREATE INDEX IDX_ing_status      ON ING_ingresso(ing_st_ingresso);
CREATE INDEX IDX_tpi_evento      ON TPI_tipo_ingresso(tpi_id_evento);
CREATE INDEX IDX_eve_dt_evento   ON EVE_evento(eve_dt_evento);
CREATE INDEX IDX_eve_organizador ON EVE_evento(eve_id_organizador);
CREATE INDEX IDX_usu_email       ON USU_usuario(usu_ds_email);
CREATE INDEX IDX_tra_comprador   ON TRA_transacao(tra_id_comprador);
CREATE INDEX IDX_not_usuario     ON NOT_notificacao(not_id_usuario);


-- ==========================================
-- PARTE 3: VIEW (Visão com JOINs)
-- ==========================================

CREATE OR REPLACE VIEW VW_resumo_vendas_evento AS
SELECT
    e.eve_id_organizador,
    e.eve_id_evento,
    e.eve_nm_evento,
    e.eve_dt_evento,
    e.eve_qt_capacidade                                             AS qt_capacidade_total,
    COUNT(i.ing_id_ingresso)                                        AS qt_ingressos_vendidos,
    (e.eve_qt_capacidade - COUNT(i.ing_id_ingresso)::INTEGER)       AS qt_capacidade_restante,
    COALESCE(
        SUM(CASE WHEN i.ing_id_ingresso IS NOT NULL THEN tpi.tpi_vl_preco ELSE 0 END),
        0
    )                                                               AS vl_receita_total
FROM EVE_evento e
LEFT JOIN TPI_tipo_ingresso tpi
       ON e.eve_id_evento = tpi.tpi_id_evento
LEFT JOIN ING_ingresso i
       ON tpi.tpi_id_tipo_ingresso = i.ing_id_tipo_ingresso
      AND i.ing_st_ingresso IN ('A', 'U')
GROUP BY
    e.eve_id_organizador,
    e.eve_id_evento,
    e.eve_nm_evento,
    e.eve_dt_evento,
    e.eve_qt_capacidade;


-- ==========================================
-- PARTE 4: FUNCTION & TRIGGER (Regra de Lotação)
-- ==========================================

CREATE OR REPLACE FUNCTION FN_calcular_capacidade_restante(p_id_evento BIGINT)
RETURNS INTEGER AS $$
DECLARE
    v_capacidade_total    INTEGER;
    v_ingressos_vendidos  INTEGER;
BEGIN
    SELECT eve_qt_capacidade
    INTO   v_capacidade_total
    FROM   EVE_evento
    WHERE  eve_id_evento = p_id_evento;

    SELECT COUNT(i.ing_id_ingresso)
    INTO   v_ingressos_vendidos
    FROM   ING_ingresso i
    INNER JOIN TPI_tipo_ingresso tpi
           ON i.ing_id_tipo_ingresso = tpi.tpi_id_tipo_ingresso
    WHERE  tpi.tpi_id_evento   = p_id_evento
      AND  i.ing_st_ingresso  IN ('A', 'U');

    RETURN COALESCE(v_capacidade_total, 0) - COALESCE(v_ingressos_vendidos, 0);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION FN_TG_validar_venda()
RETURNS TRIGGER AS $$
DECLARE
    v_id_evento               BIGINT;
    v_qt_lote                 INTEGER;
    v_capacidade_restante_eve INTEGER;
    v_vendidos_lote           INTEGER;
BEGIN
    SELECT tpi_id_evento, tpi_qt_lote
    INTO   v_id_evento, v_qt_lote
    FROM   TPI_tipo_ingresso
    WHERE  tpi_id_tipo_ingresso = NEW.ing_id_tipo_ingresso;

    v_capacidade_restante_eve := FN_calcular_capacidade_restante(v_id_evento);
    IF v_capacidade_restante_eve <= 0 THEN
        RAISE EXCEPTION 'OVERBOOKING BLOQUEADO: A capacidade máxima do evento foi atingida.';
    END IF;

    SELECT COUNT(*)
    INTO   v_vendidos_lote
    FROM   ING_ingresso
    WHERE  ing_id_tipo_ingresso = NEW.ing_id_tipo_ingresso
      AND  ing_st_ingresso     IN ('A', 'U');

    IF v_vendidos_lote >= v_qt_lote THEN
        RAISE EXCEPTION 'LOTE ESGOTADO: A capacidade máxima deste lote/setor foi atingida.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER TR_validar_lotacao
BEFORE INSERT ON ING_ingresso
FOR EACH ROW EXECUTE FUNCTION FN_TG_validar_venda();


-- ==========================================
-- PARTE 5: PROCEDURE (Cancelamento)
-- ==========================================

CREATE OR REPLACE PROCEDURE PR_cancelar_transacao(
    p_id_transacao          BIGINT,
    p_id_usuario_solicitante BIGINT
)
LANGUAGE plpgsql AS $$
DECLARE
    v_id_comprador  BIGINT;
    v_dt_evento     TIMESTAMP;
    v_st_transacao  CHAR(1);
BEGIN
    SELECT tra_id_comprador, tra_st_transacao
    INTO   v_id_comprador, v_st_transacao
    FROM   TRA_transacao
    WHERE  tra_id_transacao = p_id_transacao
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Transação % não encontrada.', p_id_transacao;
    END IF;

    IF v_id_comprador != p_id_usuario_solicitante THEN
        RAISE EXCEPTION 'Violação: O usuário não é o titular desta transação.';
    END IF;

    IF v_st_transacao = 'X' THEN
        RAISE EXCEPTION 'Esta transação já se encontra cancelada.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM   ING_ingresso
        WHERE  ing_id_transacao = p_id_transacao
          AND  ing_st_ingresso  = 'U'
    ) THEN
        RAISE EXCEPTION 'Cancelamento negado: Um ou mais ingressos desta transação já foram utilizados no evento.';
    END IF;

    SELECT e.eve_dt_evento
    INTO   v_dt_evento
    FROM   ING_ingresso i
    INNER JOIN TPI_tipo_ingresso tpi ON i.ing_id_tipo_ingresso = tpi.tpi_id_tipo_ingresso
    INNER JOIN EVE_evento e          ON tpi.tpi_id_evento      = e.eve_id_evento
    WHERE  i.ing_id_transacao = p_id_transacao
    LIMIT  1;

    IF v_dt_evento <= CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION 'Cancelamento negado: O evento já iniciou ou já ocorreu.';
    END IF;

    UPDATE TRA_transacao
    SET    tra_st_transacao = 'X'
    WHERE  tra_id_transacao = p_id_transacao;

    UPDATE ING_ingresso
    SET    ing_st_ingresso = 'C'
    WHERE  ing_id_transacao = p_id_transacao;

END;
$$;


-- ==========================================
-- PARTE 6: DADOS INICIAIS (Seed)
-- ==========================================

-- Perfis do sistema
INSERT INTO PER_perfil (per_nm_perfil) VALUES ('COMPRADOR');
INSERT INTO PER_perfil (per_nm_perfil) VALUES ('ORGANIZADOR');

-- Categorias de eventos
INSERT INTO CAT_categoria (cat_nm_categoria, cat_ds_categoria) VALUES
    ('Shows',        'Apresentações musicais e artísticas'),
    ('Esportes',     'Eventos esportivos e competições'),
    ('Teatro',       'Peças teatrais e apresentações cênicas'),
    ('Conferências', 'Eventos corporativos e acadêmicos'),
    ('Festivais',    'Festivais culturais e de entretenimento'),
    ('Gastronomia',  'Feiras e festivais gastronômicos');

-- Usuários de exemplo (senha: Ticket@123)
-- OBS: Inserir pela aplicação
INSERT INTO USU_usuario (usu_nm_usuario, usu_ds_email, usu_ds_senha, usu_nu_cpf_cnpj) VALUES
    ('Comprador Teste',   'comprador@ticketcore.com',   '$2a$10$EU6FVLHDLsUjvDYS1E4fVOBVjoWTuqKM2aUUN3FCzYhuE6.lgMvlm', '12345678901'),
    ('Organizador Teste', 'organizador@ticketcore.com', '$2a$10$EU6FVLHDLsUjvDYS1E4fVOBVjoWTuqKM2aUUN3FCzYhuE6.lgMvlm', '98765432100');

-- Vínculos de perfil dos usuários de seed
-- (IDs gerados pela sequência; ajustar se os IDs não forem os esperados após inserção das categorias/perfis)
INSERT INTO USP_usuario_perfil (usp_id_usuario, usp_id_perfil)
    SELECT u.usu_id_usuario, p.per_id_perfil
    FROM USU_usuario u, PER_perfil p
    WHERE u.usu_ds_email = 'comprador@ticketcore.com' AND p.per_nm_perfil = 'COMPRADOR';

INSERT INTO USP_usuario_perfil (usp_id_usuario, usp_id_perfil)
    SELECT u.usu_id_usuario, p.per_id_perfil
    FROM USU_usuario u, PER_perfil p
    WHERE u.usu_ds_email = 'organizador@ticketcore.com' AND p.per_nm_perfil = 'ORGANIZADOR';

-- Eventos de exemplo (criados pelo organizador seed)
INSERT INTO EVE_evento
    (eve_id_organizador, eve_id_categoria, eve_nm_evento, eve_dt_evento, eve_nm_local, eve_qt_capacidade)
SELECT
    u.usu_id_usuario,
    c.cat_id_categoria,
    'Festival de Rock TicketCore',
    '2027-03-15 20:00:00',
    'Arena Central — São Paulo/SP',
    500
FROM USU_usuario u, CAT_categoria c
WHERE u.usu_ds_email = 'organizador@ticketcore.com' AND c.cat_nm_categoria = 'Shows';

INSERT INTO EVE_evento
    (eve_id_organizador, eve_id_categoria, eve_nm_evento, eve_dt_evento, eve_nm_local, eve_qt_capacidade)
SELECT
    u.usu_id_usuario,
    c.cat_id_categoria,
    'Hamlet — Temporada 2027',
    '2027-04-10 19:30:00',
    'Teatro Municipal — Rio de Janeiro/RJ',
    200
FROM USU_usuario u, CAT_categoria c
WHERE u.usu_ds_email = 'organizador@ticketcore.com' AND c.cat_nm_categoria = 'Teatro';

-- Tipos de ingresso dos eventos de seed
INSERT INTO TPI_tipo_ingresso (tpi_id_evento, tpi_nm_tipo, tpi_vl_preco, tpi_qt_lote)
SELECT e.eve_id_evento, 'Pista', 150.00, 400
FROM EVE_evento e WHERE e.eve_nm_evento = 'Festival de Rock TicketCore';

INSERT INTO TPI_tipo_ingresso (tpi_id_evento, tpi_nm_tipo, tpi_vl_preco, tpi_qt_lote)
SELECT e.eve_id_evento, 'VIP', 350.00, 100
FROM EVE_evento e WHERE e.eve_nm_evento = 'Festival de Rock TicketCore';

INSERT INTO TPI_tipo_ingresso (tpi_id_evento, tpi_nm_tipo, tpi_vl_preco, tpi_qt_lote)
SELECT e.eve_id_evento, 'Plateia', 80.00, 150
FROM EVE_evento e WHERE e.eve_nm_evento = 'Hamlet — Temporada 2027';

INSERT INTO TPI_tipo_ingresso (tpi_id_evento, tpi_nm_tipo, tpi_vl_preco, tpi_qt_lote)
SELECT e.eve_id_evento, 'Camarote', 200.00, 50
FROM EVE_evento e WHERE e.eve_nm_evento = 'Hamlet — Temporada 2027';

-- Transação de exemplo: comprador compra 1 ingresso Pista do Festival de Rock
INSERT INTO TRA_transacao (tra_id_comprador, tra_st_transacao, tra_vl_total)
SELECT u.usu_id_usuario, 'C', 150.00
FROM USU_usuario u WHERE u.usu_ds_email = 'comprador@ticketcore.com';

-- Ingresso gerado para a transação acima
INSERT INTO ING_ingresso (ing_id_transacao, ing_id_tipo_ingresso, ing_cd_acesso, ing_st_ingresso)
SELECT
    t.tra_id_transacao,
    ti.tpi_id_tipo_ingresso,
    'A1B2C3D4E5F6',
    'A'
FROM TRA_transacao t
JOIN USU_usuario u ON u.usu_id_usuario = t.tra_id_comprador
JOIN TPI_tipo_ingresso ti ON ti.tpi_nm_tipo = 'Pista'
JOIN EVE_evento e ON e.eve_id_evento = ti.tpi_id_evento
WHERE u.usu_ds_email = 'comprador@ticketcore.com';

-- Notificações de exemplo
INSERT INTO NOT_notificacao (not_id_usuario, not_ds_mensagem)
SELECT usu_id_usuario, 'Sua compra foi confirmada! 1 ingresso para Festival de Rock TicketCore.'
FROM USU_usuario WHERE usu_ds_email = 'comprador@ticketcore.com';

INSERT INTO NOT_notificacao (not_id_usuario, not_ds_mensagem)
SELECT usu_id_usuario, 'Nova venda confirmada para o evento Festival de Rock TicketCore. Valor: R$ 150,00.'
FROM USU_usuario WHERE usu_ds_email = 'organizador@ticketcore.com';
